name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build apk --debug 
            flutter build web --release
          working-directory: ./deployproj
          
        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/debug/*"
            tag: v1.0.${{ github.run_number }}
              
          # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:mentoring-app-17e5b
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./deployproj
